fieldLayouts:
  d6acb5fa-6505-4814-b6ab-db260998652c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: adea277a-c5a6-4df7-91c5-34332938435d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3293cfd7-675a-45cc-903d-6ed74af35c56
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 8f98af24-6aee-44bc-98c7-28434d3c46d8 # About testCraft Coffee
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
