fieldLayouts:
  d6acb5fa-6505-4814-b6ab-db260998652c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: adea277a-c5a6-4df7-91c5-34332938435d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 781ae06f-d2eb-4d6b-96bb-4c9fdde485bc # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9cabc4c-38aa-4970-a2b8-3f5abf1cf751
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa350295-a7d7-4d0e-b49e-f6b1f4617c33 # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79bdb145-68df-4b1f-94a0-051bdd48f34e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9896fa03-c44b-42f0-a504-3f5a4dc2cb62 # Page Copy
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9562829-f202-4641-af96-4ddf1eb1495c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3293cfd7-675a-45cc-903d-6ed74af35c56
        userCondition: null
handle: default
hasTitleField: true
name: About
section: 8f98af24-6aee-44bc-98c7-28434d3c46d8 # About testCraft Coffee
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
