fieldLayouts:
  2ab23d5e-5405-403f-9579-3bfb7a2543c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ad5410c7-a1aa-4349-89e4-93aa9c052dc6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04175dd2-255d-4455-aa00-ff557ed530aa # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8335d587-82aa-46a2-8b55-eb943c78c3b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cae9ff85-31c9-4c58-87e6-a62c3a58f9dd # News Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d506ce-5589-4806-b75e-aeddfc5cfbb0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e3eb55fc-fb45-407a-9fd2-10512287290c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 07d5f631-aaed-46ff-af12-c939e4b7766a # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: Headline
titleTranslationKeyFormat: null
titleTranslationMethod: site
