fieldLayouts:
  e05eb1c7-17bf-40e4-8e4b-854c8e902604:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cd60282c-e964-409b-b6d3-96924b1b78d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 285fcf5f-ac35-4a41-94a0-eaa962d74329
        userCondition: null
fs: drinks
handle: drinks
name: Drinks
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
