columnSuffix: null
contentColumnType: string
fieldGroup: 738ad5d8-5c81-4e1f-9ff9-03a1cca87e1f # Drinks
handle: drinkImage
instructions: null
name: 'Drink Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:b842a9a8-8a06-4cac-b2cf-ca9e70537e37' # Drinks
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:b842a9a8-8a06-4cac-b2cf-ca9e70537e37' # Drinks
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: 'Add a drink image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:b842a9a8-8a06-4cac-b2cf-ca9e70537e37' # Drinks
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
