defaultPlacement: end
enableVersioning: true
handle: aboutTestcraftCoffee
name: 'About testCraft Coffee'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e78cc242-5295-4b17-84e1-67c6da9179e7: # testCraft
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: 'about/{slug}'
structure:
  maxLevels: null
  uid: ffacea9f-93f4-42fa-b036-63c758ad005c
type: structure
