defaultPlacement: end
enableVersioning: true
handle: drinks
name: Drinks
propagationMethod: all
siteSettings:
  e78cc242-5295-4b17-84e1-67c6da9179e7: # testCraft
    enabledByDefault: true
    hasUrls: true
    template: drinks/_entry
    uriFormat: 'drinks/{slug}'
type: channel
